name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js and pnpm with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # version with cache support
      with:
        run_install: true
        cache: true
