services:
  mx-core:
    image: ${MX_CORE_IMAGE:-mx-core:latest}
    ports:
      - target: 2333
        published: ${MX_PORT:-2333}
        protocol: tcp
        mode: ingress

    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      TZ: ${TZ:-Asia/Shanghai}
      PORT: "2333"
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-localhost:*}

      # MongoDB (service in this stack)
      # NOTE: In Docker Swarm stack, service names are prefixed with the stack name,
      # e.g. `mx-core_mongo` / `mx-core_redis`.
      DB_CONNECTION_STRING: mongodb://mx-core_mongo:27017/mx-space

      # Redis (service in this stack)
      REDIS_HOST: mx-core_redis
      REDIS_PORT: "6379"

      # Security (optional)
      ENCRYPT_ENABLE: ${ENCRYPT_ENABLE:-true}
      ENCRYPT_KEY: ${ENCRYPT_KEY:-}
      JWT_SECRET: ${JWT_SECRET:-}
      JWT_EXPIRE: ${JWT_EXPIRE:-}

      DISABLE_CACHE: ${DISABLE_CACHE:-false}
      DEBUG: ${DEBUG:-false}
      DEBUG_MEMORY_DUMP: ${DEBUG_MEMORY_DUMP:-false}

    volumes:
      - type: bind
        source: ./data/mx-space
        target: /root/.mx-space

    depends_on:
      - mongo
      - redis
    networks:
      default: {}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:2333/api/v2/ping"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s

    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        order: stop-first
        monitor: 30s

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - type: bind
        source: ./data/redis
        target: /data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 20s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      default: {}

  mongo:
    image: mongo:7
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' | grep 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      default: {}

networks:
  default:
    driver: overlay
    attachable: true
