packages:
  - packages/*
  - apps/*
allowBuilds:
  "@nestjs/core": true
  '@parcel/watcher': false
  "@swc/core": true
  cpu-features: false
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: false
  protobufjs: false
  redis-memory-server: true
  sharp: true
  simple-git-hooks: true
  ssh2: false
  unrs-resolver: true
  workerd: true
overrides:
  "eslint-plugin-react-compiler>zod": 3.25.76
  "get-pixels@^3>request": ./external/request
  mongodb: ~7.2.0
  pino: ./external/pino
  rolldown: 1.0.1
  semver: 7.8.0
  typescript: 6.0.3
  whatwg-url: 16.0.1
  zod: 4.4.3
publicHoistPattern:
  - "*fastify*"
  - mongodb
  - "*eslint*"
  - "*webpack*"
strictPeerDependencies: false
