packages:
  - packages/*
  - apps/*
catalog:
  '@algolia/client-search': ^4.22.1
  '@antfu/install-pkg': 1.0.0
  '@aws-sdk/client-s3': 3.802.0
  '@babel/core': 7.27.1
  '@babel/plugin-transform-modules-commonjs': 7.27.1
  '@babel/plugin-transform-typescript': 7.27.1
  '@babel/types': ^7.27.1
  '@fastify/cookie': 11.0.2
  '@fastify/multipart': 9.0.3
  '@fastify/static': 8.1.1
  '@innei/next-async': 0.3.0
  '@innei/prettier': 0.15.0
  '@innei/pretty-logger-nestjs': 0.3.3
  '@keyv/redis': 4.4.0
  '@langchain/core': 0.3.51
  '@langchain/openai': 0.5.10
  '@modelcontextprotocol/sdk': 1.11.0
  '@nestjs/cache-manager': 3.0.1
  '@nestjs/cli': 11.0.7
  '@nestjs/common': 11.1.0
  '@nestjs/core': 11.1.0
  '@nestjs/event-emitter': 3.0.1
  '@nestjs/mapped-types': ^2.1.0
  '@nestjs/platform-fastify': 11.1.0
  '@nestjs/platform-socket.io': 11.1.0
  '@nestjs/schedule': 6.0.0
  '@nestjs/schematics': 11.0.5
  '@nestjs/testing': 11.1.0
  '@nestjs/throttler': 6.4.0
  '@nestjs/websockets': 11.1.0
  '@simplewebauthn/server': 10.0.1
  '@socket.io/redis-adapter': 8.3.0
  '@socket.io/redis-emitter': 5.1.0
  '@swc/core': 1.11.24
  '@sxzz/eslint-config': 6.1.1
  '@typegoose/auto-increment': 4.13.0
  '@typegoose/typegoose': 12.15.0
  '@types/babel__core': 7.20.5
  '@types/bcryptjs': ^3.0.0
  '@types/cls-hooked': ^4.3.9
  '@types/ejs': 3.1.5
  '@types/get-image-colors': 4.0.5
  '@types/js-yaml': 4.0.9
  '@types/jsonwebtoken': 9.0.9
  '@types/lodash': 4.17.16
  '@types/mime-types': 2.1.4
  '@types/mongoose-aggregate-paginate-v2': 1.0.12
  '@types/node': 22.15.3
  '@types/nodemailer': 6.4.17
  '@types/qs': 6.9.18
  '@types/remove-markdown': 0.3.4
  '@types/semver': 7.7.0
  '@types/ua-parser-js': 0.7.39
  '@types/validator': 13.15.0
  '@vercel/ncc': 0.38.3
  algoliasearch: 4.24.0
  axios: ^1.9.0
  axios-retry: 4.5.0
  bcryptjs: ^3.0.2
  better-auth: 1.2.5
  blurhash: 2.0.5
  cache-manager: 6.4.2
  class-transformer: 0.5.1
  class-validator: 0.13.2
  class-validator-jsonschema: npm:@innei/class-validator-jsonschema@3.1.2
  cls-hooked: ^4.2.2
  commander: 13.1.0
  cron: ^3.5.0
  cross-env: 7.0.3
  dayjs: 1.11.13
  ejs: 3.1.10
  eslint: ^9.24.0
  form-data: 4.0.2
  inquirer: ^10.2.2
  ioredis: 5.6.1
  isbot: 5.1.27
  js-yaml: ^4.1.0
  json5: 2.2.3
  jsonwebtoken: 9.0.2
  jszip: 3.10.1
  keyv: 5.3.3
  langchain: 0.3.24
  linkedom: 0.18.10
  lint-staged: 15.5.0
  lodash: ^4.17.21
  lru-cache: 11.1.0
  marked: 15.0.11
  mime-types: ^3.0.1
  mkdirp: ^3.0.1
  mongoose: 8.14.1
  mongoose-aggregate-paginate-v2: 1.1.4
  mongoose-autopopulate: 1.1.0
  mongoose-lean-getters: 2.2.1
  mongoose-lean-virtuals: 1.1.0
  mongoose-paginate-v2: 1.9.0
  nanoid: 5.1.5
  node-machine-id: 1.1.12
  nodemailer: 7.0.0
  openai: 4.97.0
  pluralize: ^8.0.0
  prettier: 3.5.3
  qs: 6.14.0
  reflect-metadata: 0.2.2
  remove-markdown: 0.6.2
  remove-md-codeblock: 0.0.4
  rimraf: 6.0.1
  rxjs: 7.8.2
  semver: 7.7.1
  sharp: 0.34.1
  simple-git-hooks: 2.12.1
  slugify: 1.6.6
  snakecase-keys: 6.0.0
  socket.io: ^4.8.1
  source-map-support: ^0.5.21
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  tsup: 8.4.0
  typescript: 5.8.3
  ua-parser-js: 2.0.3
  unplugin-swc: 1.5.2
  vite: 5.4.10
  vite-tsconfig-paths: 5.1.4
  vitest: 1.5.2
  vm2: 3.9.19
  wildcard-match: 5.1.4
  xss: 1.0.15
  zod: 3.24.3
  zx: 7.2.3
  zx-cjs: 7.0.7-0
catalogs:
  conflicts_@types/node_22_14_0:
    '@types/node': 22.14.0
