import * as monaco from 'monaco-editor'

export const GITHUB_LIGHT_THEME = 'github-light'
export const GITHUB_DARK_THEME = 'github-dark'

let registered = false

export function ensureGithubThemesRegistered() {
  if (registered) return
  registered = true

  monaco.editor.defineTheme(GITHUB_LIGHT_THEME, {
    base: 'vs',
    inherit: true,
    rules: [
      { token: '', foreground: '1f2328', background: 'ffffff' },
      { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
      { token: 'comment.html', foreground: '6e7781', fontStyle: 'italic' },
      { token: 'comment.ejs', foreground: '6e7781', fontStyle: 'italic' },
      { token: 'comment.content.html', foreground: '6e7781' },
      { token: 'comment.content.ejs', foreground: '6e7781' },
      { token: 'string', foreground: '0a3069' },
      { token: 'string.ejs', foreground: '0a3069' },
      { token: 'string.escape', foreground: '0a3069' },
      { token: 'string.escape.ejs', foreground: '0a3069' },
      { token: 'string.invalid', foreground: 'cf222e' },
      { token: 'number', foreground: '0550ae' },
      { token: 'number.ejs', foreground: '0550ae' },
      { token: 'keyword', foreground: 'cf222e' },
      { token: 'keyword.ejs', foreground: 'cf222e' },
      { token: 'identifier', foreground: '1f2328' },
      { token: 'identifier.ejs', foreground: '953800' },
      { token: 'delimiter', foreground: '24292f' },
      { token: 'delimiter.ejs', foreground: '24292f' },
      { token: 'delimiter.html', foreground: '24292f' },
      { token: 'tag', foreground: '116329' },
      { token: 'tag.html', foreground: '116329' },
      { token: 'metatag', foreground: '116329' },
      { token: 'metatag.html', foreground: '116329' },
      { token: 'metatag.ejs', foreground: '8250df', fontStyle: 'bold' },
      { token: 'metatag.content.html', foreground: '0550ae' },
      { token: 'attribute.name', foreground: '0550ae' },
      { token: 'attribute.name.html', foreground: '0550ae' },
      { token: 'attribute.value', foreground: '0a3069' },
      { token: 'attribute.value.html', foreground: '0a3069' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#1f2328',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#0969da33',
      'editor.inactiveSelectionBackground': '#afb8c133',
      'editorCursor.foreground': '#1f2328',
      'editorLineNumber.foreground': '#8c959f',
      'editorLineNumber.activeForeground': '#1f2328',
      'editorIndentGuide.background': '#eaeef2',
      'editorIndentGuide.activeBackground': '#d0d7de',
      'editorGutter.background': '#ffffff',
      'editorWhitespace.foreground': '#afb8c1',
      'editorBracketMatch.background': '#0969da26',
      'editorBracketMatch.border': '#0969da',
      'editorSuggestWidget.background': '#ffffff',
      'editorSuggestWidget.border': '#d0d7de',
      'editorSuggestWidget.foreground': '#1f2328',
      'editorSuggestWidget.selectedBackground': '#ddf4ff',
      'editorWidget.background': '#ffffff',
      'editorWidget.border': '#d0d7de',
      'scrollbarSlider.background': '#afb8c133',
      'scrollbarSlider.hoverBackground': '#afb8c166',
      'scrollbarSlider.activeBackground': '#afb8c199',
    },
  })

  monaco.editor.defineTheme(GITHUB_DARK_THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'e6edf3', background: '0d1117' },
      { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'comment.html', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'comment.ejs', foreground: '8b949e', fontStyle: 'italic' },
      { token: 'comment.content.html', foreground: '8b949e' },
      { token: 'comment.content.ejs', foreground: '8b949e' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'string.ejs', foreground: 'a5d6ff' },
      { token: 'string.escape', foreground: 'a5d6ff' },
      { token: 'string.escape.ejs', foreground: 'a5d6ff' },
      { token: 'string.invalid', foreground: 'ff7b72' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'number.ejs', foreground: '79c0ff' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'keyword.ejs', foreground: 'ff7b72' },
      { token: 'identifier', foreground: 'e6edf3' },
      { token: 'identifier.ejs', foreground: 'ffa657' },
      { token: 'delimiter', foreground: 'c9d1d9' },
      { token: 'delimiter.ejs', foreground: 'c9d1d9' },
      { token: 'delimiter.html', foreground: 'c9d1d9' },
      { token: 'tag', foreground: '7ee787' },
      { token: 'tag.html', foreground: '7ee787' },
      { token: 'metatag', foreground: '7ee787' },
      { token: 'metatag.html', foreground: '7ee787' },
      { token: 'metatag.ejs', foreground: 'd2a8ff', fontStyle: 'bold' },
      { token: 'metatag.content.html', foreground: '79c0ff' },
      { token: 'attribute.name', foreground: '79c0ff' },
      { token: 'attribute.name.html', foreground: '79c0ff' },
      { token: 'attribute.value', foreground: 'a5d6ff' },
      { token: 'attribute.value.html', foreground: 'a5d6ff' },
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#e6edf3',
      'editor.lineHighlightBackground': '#161b22',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#3392ff44',
      'editor.inactiveSelectionBackground': '#3392ff22',
      'editorCursor.foreground': '#e6edf3',
      'editorLineNumber.foreground': '#6e7681',
      'editorLineNumber.activeForeground': '#e6edf3',
      'editorIndentGuide.background': '#21262d',
      'editorIndentGuide.activeBackground': '#30363d',
      'editorGutter.background': '#0d1117',
      'editorWhitespace.foreground': '#484f58',
      'editorBracketMatch.background': '#3392ff33',
      'editorBracketMatch.border': '#3392ff',
      'editorSuggestWidget.background': '#161b22',
      'editorSuggestWidget.border': '#30363d',
      'editorSuggestWidget.foreground': '#e6edf3',
      'editorSuggestWidget.selectedBackground': '#1f6feb33',
      'editorWidget.background': '#161b22',
      'editorWidget.border': '#30363d',
      'scrollbarSlider.background': '#484f5833',
      'scrollbarSlider.hoverBackground': '#484f5866',
      'scrollbarSlider.activeBackground': '#484f5899',
    },
  })
}
