name: Install MongoDB and Redis Binaries
description: 'Install MongoDB and Redis binaries for testing'

runs:
  using: 'composite'
  steps:
    - name: Install MongoDB
      shell: bash
      run: |
        sudo apt-get install gnupg curl
        curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | \
        sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
        --dearmor
        echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] http://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | \
        sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org

    - name: Install Redis
      shell: bash
      run: |
        sudo apt-get install -y redis-server