import type { IConfig } from './configs.interface'

export const generateDefaultConfig: () => IConfig = () => ({
  seo: {
    title: 'My Little World',
    description: 'Hi, welcome!',
    icon: '',
    iconDark: '',
    keywords: [],
  },
  url: {
    wsUrl: 'http://localhost:2333', // todo
    adminUrl: 'http://localhost:2333/proxy/qaqdmin',
    serverUrl: 'http://localhost:2333',
    webUrl: 'http://localhost:2323',
  },
  mailOptions: {
    enable: false,
    provider: 'smtp',
    from: '',
    smtp: {
      user: '',
      pass: '',
      options: {
        host: '',
        port: 465,
        secure: true,
      },
    },
    resend: {
      apiKey: '',
    },
    rateLimit: 10,
    retryCount: 3,
  },
  commentOptions: {
    antiSpam: false,
    aiReview: false,
    aiReviewType: 'binary',
    aiReviewThreshold: 5,
    testAiReview: '__action__',
    disableComment: false,
    allowGuestComment: true,
    blockIps: [],
    disableNoChinese: false,
    recordIpLocation: true,
    spamKeywords: [],
    commentShouldAudit: false,
  },
  barkOptions: {
    enable: false,
    key: '',
    serverUrl: 'https://api.day.app',
    enableComment: true,
    enableThrottleGuard: false,
  },
  friendLinkOptions: {
    allowApply: true,
    allowSubPath: false,
    enableAvatarInternalization: true,
  },
  backupOptions: {
    enable: true,
    endpoint: null!,
    region: null!,
    bucket: null!,
    secretId: null!,
    secretKey: null!,
  },
  imageStorageOptions: {
    enable: false,
    endpoint: null!,
    secretId: null!,
    secretKey: null!,
    bucket: null!,
    region: 'auto',
    customDomain: '',
    prefix: '',
    commentUploadPrefix: '',
  },
  fileUploadOptions: {
    enableCustomNaming: false,
    filenameTemplate: '{Y}{m}{d}/{md5-16}{ext}',
    pathTemplate: '{type}',
  },
  commentUploadOptions: {
    enable: true,
    pendingTtlMinutes: 120,
    detachedTtlMinutes: 30,
    cronIntervalMinutes: 15,
    singleFileSizeMB: 5,
    commentImageMaxCount: 4,
    readerHourlyUploadCount: 10,
    readerTotalActiveBytesMB: 50,
    readerMinAccountAgeHours: 0,
    readerMinCommentCount: 0,
    deleteFilesOnSpam: true,
    mimeWhitelist: ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
  },
  baiduSearchOptions: { enable: false, token: null! },
  bingSearchOptions: { enable: false, token: null! },
  adminExtra: {
    enableAdminProxy: true,

    background: '',
    gaodemapKey: null!,
  },
  featureList: {
    emailSubscribe: false,
  },
  thirdPartyServiceIntegration: {
    github: { enabled: true, token: '' },
    tmdb: { enabled: false, apiKey: '' },
    bangumi: { enabled: true, accessToken: '' },
    neodb: { enabled: true },
    arxiv: { enabled: true },
    leetcode: { enabled: true },
    neteaseMusic: { enabled: true },
    qqMusic: { enabled: true },
    openGraph: {
      enabled: true,
      fetchMode: 'fetch',
      timeoutMs: 8000,
      maxBodyBytes: 524_288,
      screenshot: {
        enabled: false,
        maxItems: 500,
        maxTotalBytes: 100 * 1024 * 1024,
        maxBytesPerImage: 512 * 1024,
        webpQuality: 75,
      },
    },
  },

  authSecurity: {
    disablePasswordLogin: false,
  },
  ai: {
    providers: [],
    summaryModel: undefined,
    writerModel: undefined,
    commentReviewModel: undefined,
    enableSummary: false,
    enableAutoGenerateSummaryOnCreate: false,
    enableAutoGenerateSummaryOnUpdate: false,
    summaryTargetLanguages: [],
    summaryMinTextLength: 100,
    enableTranslationReview: false,
    translationReviewModel: undefined,
    translationReviewScoreThreshold: 85,
    insightsModel: undefined,
    insightsTranslationModel: undefined,
    enableInsights: false,
    enableAutoGenerateInsightsOnCreate: false,
    enableAutoGenerateInsightsOnUpdate: false,
    enableAutoTranslateInsights: false,
    insightsTargetLanguages: [],
    insightsMinTextLength: 300,
    echoModel: undefined,
    embeddingModel: undefined,
    personaDistillModel: undefined,
    enableEcho: false,
    enableAutoGenerateEchoOnCreate: false,
    echoDailyQuota: 200,
    echoRetrievalTopK: 5,
    echoRetrievalMinSimilarity: 0.72,
    echoExemplarsCount: 4,
    aiEmbedding: {
      chunkMaxTokens: 500,
      chunkOverlapTokens: 50,
      backfillBatchSize: 50,
      defaultMinSimilarity: 0.7,
      defaultTopK: 5,
    },
    aiPersona: {
      distillSampleMaxTokens: 60_000,
      exemplarsLengthMin: 200,
      exemplarsLengthMax: 800,
      exemplarsCandidateCacheTtlSec: 3600,
    },
    aiMemory: {
      recallTopK: 5,
      recallMinSimilarity: 0.7,
    },
  },
  oauth: {
    providers: [],
    secrets: {},
    public: {},
  },
})
