export enum AppErrorCode {
  // generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  NO_CONTENT_MODIFIABLE = 'NO_CONTENT_MODIFIABLE',
  DEMO_FORBIDDEN = 'DEMO_FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  CONTENT_NOT_FOUND_CANT_PROCESS = 'CONTENT_NOT_FOUND_CANT_PROCESS',
  MAX_COUNT_LIMIT = 'MAX_COUNT_LIMIT',
  MASTER_LOST = 'MASTER_LOST',
  CANNOT_GET_IP = 'CANNOT_GET_IP',
  ENTRY_NOT_FOUND = 'ENTRY_NOT_FOUND',
  REF_MODEL_NOT_FOUND = 'REF_MODEL_NOT_FOUND',

  // validation
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  INVALID_BODY = 'INVALID_BODY',
  INVALID_SLUG = 'INVALID_SLUG',
  INVALID_NAME = 'INVALID_NAME',
  INVALID_REFERENCE = 'INVALID_REFERENCE',
  INVALID_ORDER_VALUE = 'INVALID_ORDER_VALUE',
  INVALID_SEARCH_TYPE = 'INVALID_SEARCH_TYPE',
  INVALID_ROOM_NAME = 'INVALID_ROOM_NAME',
  INVALID_SUBSCRIBE_TYPE = 'INVALID_SUBSCRIBE_TYPE',
  INVALID_VIEW = 'INVALID_VIEW',
  SLUG_NOT_AVAILABLE = 'SLUG_NOT_AVAILABLE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',

  // ack
  ACK_INVALID_PAYLOAD = 'ACK_INVALID_PAYLOAD',

  // ai
  AI_CONTENT_MISSING = 'AI_CONTENT_MISSING',
  AI_INVALID_PARAMETER = 'AI_INVALID_PARAMETER',
  AI_INVALID_QUERY_TYPE = 'AI_INVALID_QUERY_TYPE',
  AI_NOT_ENABLED = 'AI_NOT_ENABLED',
  AI_KEY_EXPIRED = 'AI_KEY_EXPIRED',
  AI_PROCESSING = 'AI_PROCESSING',
  AI_PROVIDER_DISABLED = 'AI_PROVIDER_DISABLED',
  AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
  AI_REVIEW_NOT_ENABLED = 'AI_REVIEW_NOT_ENABLED',
  AI_RESULT_PARSING_ERROR = 'AI_RESULT_PARSING_ERROR',
  AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
  AI_TRANSLATION_NOT_FOUND = 'AI_TRANSLATION_NOT_FOUND',

  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_ALREADY_COMPLETED = 'TASK_ALREADY_COMPLETED',
  TASK_CANNOT_RETRY = 'TASK_CANNOT_RETRY',

  // auth
  AUTH_DEVICE_FLOW_PENDING = 'AUTH_DEVICE_FLOW_PENDING',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_NOT_LOGGED_IN = 'AUTH_NOT_LOGGED_IN',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',
  AUTH_CHALLENGE_MISSING = 'AUTH_CHALLENGE_MISSING',
  AUTH_CHALLENGE_EXPIRED = 'AUTH_CHALLENGE_EXPIRED',
  AUTH_REGISTRATION_MISSING = 'AUTH_REGISTRATION_MISSING',
  AUTH_USERNAME_INCORRECT = 'AUTH_USERNAME_INCORRECT',
  AUTH_PASSWORD_INCORRECT = 'AUTH_PASSWORD_INCORRECT',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_USER_ID_NOT_FOUND = 'AUTH_USER_ID_NOT_FOUND',
  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  PASSWORD_LOGIN_DISABLED = 'PASSWORD_LOGIN_DISABLED',
  PASSWORD_SAME_AS_OLD = 'PASSWORD_SAME_AS_OLD',

  // category
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_POSTS = 'CATEGORY_HAS_POSTS',

  // comment
  COMMENT_DISABLED = 'COMMENT_DISABLED',
  COMMENT_FORBIDDEN = 'COMMENT_FORBIDDEN',
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_TOO_DEEP = 'COMMENT_TOO_DEEP',
  COMMENT_POST_NOT_EXISTS = 'COMMENT_POST_NOT_EXISTS',
  COMMENT_IMAGE_CAP_EXCEEDED = 'COMMENT_IMAGE_CAP_EXCEEDED',
  COMMENT_UPLOAD_DISABLED = 'COMMENT_UPLOAD_DISABLED',
  COMMENT_UPLOAD_FILE_TOO_LARGE = 'COMMENT_UPLOAD_FILE_TOO_LARGE',
  COMMENT_UPLOAD_INVALID_MIME = 'COMMENT_UPLOAD_INVALID_MIME',
  COMMENT_UPLOAD_FILE_NOT_OWNED = 'COMMENT_UPLOAD_FILE_NOT_OWNED',
  COMMENT_UPLOAD_FILE_ALREADY_BOUND = 'COMMENT_UPLOAD_FILE_ALREADY_BOUND',
  COMMENT_UPLOAD_RATE_LIMITED = 'COMMENT_UPLOAD_RATE_LIMITED',
  COMMENT_UPLOAD_QUOTA_EXCEEDED = 'COMMENT_UPLOAD_QUOTA_EXCEEDED',
  COMMENT_UPLOAD_ACCOUNT_TOO_NEW = 'COMMENT_UPLOAD_ACCOUNT_TOO_NEW',
  COMMENT_UPLOAD_INSUFFICIENT_COMMENTS = 'COMMENT_UPLOAD_INSUFFICIENT_COMMENTS',

  // config
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  CONFIG_VALIDATION_FAILED = 'CONFIG_VALIDATION_FAILED',

  // cron
  CRON_NOT_FOUND = 'CRON_NOT_FOUND',
  INVALID_CRON_METHOD = 'INVALID_CRON_METHOD',
  FUNCTION_NOT_FOUND = 'FUNCTION_NOT_FOUND',

  // draft
  DRAFT_NOT_FOUND = 'DRAFT_NOT_FOUND',
  DRAFT_HISTORY_NOT_FOUND = 'DRAFT_HISTORY_NOT_FOUND',

  // document / helper
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  HELPER_DOCUMENT_NOT_FOUND = 'HELPER_DOCUMENT_NOT_FOUND',

  // email
  EMAIL_TEMPLATE_NOT_FOUND = 'EMAIL_TEMPLATE_NOT_FOUND',

  // enrichment
  ENRICHMENT_BROWSER_MODE_REQUIRED = 'ENRICHMENT_BROWSER_MODE_REQUIRED',
  ENRICHMENT_CAPTURE_FAILED = 'ENRICHMENT_CAPTURE_FAILED',
  ENRICHMENT_NOT_FOUND = 'ENRICHMENT_NOT_FOUND',
  ENRICHMENT_SCREENSHOT_DISABLED = 'ENRICHMENT_SCREENSHOT_DISABLED',

  // file
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_EXISTS = 'FILE_EXISTS',
  FILE_RENAME_FAILED = 'FILE_RENAME_FAILED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_STORAGE_NOT_CONFIGURED = 'FILE_STORAGE_NOT_CONFIGURED',
  FILE_UPLOAD_DISABLED = 'FILE_UPLOAD_DISABLED',
  FILE_UPLOAD_NOT_AUTHORIZED = 'FILE_UPLOAD_NOT_AUTHORIZED',
  MIME_ZIP_REQUIRED = 'MIME_ZIP_REQUIRED',

  // init
  INIT_ALREADY_COMPLETED = 'INIT_ALREADY_COMPLETED',
  INIT_FORBIDDEN = 'INIT_FORBIDDEN',
  INIT_INVALID_BODY = 'INIT_INVALID_BODY',
  INIT_INVALID_MIME_TYPE = 'INIT_INVALID_MIME_TYPE',

  // link
  LINK_APPLY_DISABLED = 'LINK_APPLY_DISABLED',
  LINK_NOT_FOUND = 'LINK_NOT_FOUND',
  LINK_DISABLED = 'LINK_DISABLED',
  SUBPATH_LINK_DISABLED = 'SUBPATH_LINK_DISABLED',
  DUPLICATE_LINK = 'DUPLICATE_LINK',
  LINK_AVATAR_VALIDATION_FAILED = 'LINK_AVATAR_VALIDATION_FAILED',

  // meta preset
  META_PRESET_KEY_EXISTS = 'META_PRESET_KEY_EXISTS',
  META_PRESET_NOT_FOUND = 'META_PRESET_NOT_FOUND',
  BUILTIN_PRESET_CANNOT_DELETE = 'BUILTIN_PRESET_CANNOT_DELETE',

  // note
  NOTE_FORBIDDEN = 'NOTE_FORBIDDEN',
  NOTE_NOT_FOUND = 'NOTE_NOT_FOUND',
  NOTE_PASSWORD_REQUIRED = 'NOTE_PASSWORD_REQUIRED',

  // owner / reader / user
  OWNER_NOT_FOUND = 'OWNER_NOT_FOUND',
  READER_NOT_FOUND = 'READER_NOT_FOUND',
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // page
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',

  // project
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_NAME_TAKEN = 'PROJECT_NAME_TAKEN',

  // post
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_UNPUBLISHED = 'POST_UNPUBLISHED',
  POST_HIDDEN_OR_ENCRYPTED = 'POST_HIDDEN_OR_ENCRYPTED',
  POST_RELATED_NOT_EXISTS = 'POST_RELATED_NOT_EXISTS',
  POST_SELF_RELATION = 'POST_SELF_RELATION',

  // recently
  RECENTLY_NOT_FOUND = 'RECENTLY_NOT_FOUND',

  // backup
  BACKUP_NOT_ENABLED = 'BACKUP_NOT_ENABLED',

  // serverless
  SERVERLESS_ERROR = 'SERVERLESS_ERROR',
  SERVERLESS_NO_PERMISSION = 'SERVERLESS_NO_PERMISSION',

  // snippet
  SNIPPET_NOT_FOUND = 'SNIPPET_NOT_FOUND',
  SNIPPET_EXISTS = 'SNIPPET_EXISTS',
  SNIPPET_PRIVATE = 'SNIPPET_PRIVATE',
  SNIPPET_INVALID_JSON = 'SNIPPET_INVALID_JSON',
  SNIPPET_INVALID_JSON5 = 'SNIPPET_INVALID_JSON5',
  SNIPPET_INVALID_YAML = 'SNIPPET_INVALID_YAML',
  SNIPPET_INVALID_FUNCTION = 'SNIPPET_INVALID_FUNCTION',

  // subscribe
  SUBSCRIBE_NOT_ENABLED = 'SUBSCRIBE_NOT_ENABLED',
  SUBSCRIBE_TYPE_EMPTY = 'SUBSCRIBE_TYPE_EMPTY',
  ALREADY_SUPPORTED = 'ALREADY_SUPPORTED',

  // topic
  TOPIC_NOT_FOUND = 'TOPIC_NOT_FOUND',

  // webhook
  WEBHOOK_EVENT_NOT_FOUND = 'WEBHOOK_EVENT_NOT_FOUND',
  WEBHOOK_NOT_FOUND = 'WEBHOOK_NOT_FOUND',

  // bing
  BING_API_FAILED = 'BING_API_FAILED',
  BING_KEY_INVALID = 'BING_KEY_INVALID',
  BING_DOMAIN_INVALID = 'BING_DOMAIN_INVALID',
}
