export const DEFAULT_SUMMARY_LANG = 'zh'

export const LANGUAGE_CODE_TO_NAME = {
  ar: 'Arabic',
  bg: 'Bulgarian',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  en: 'English',
  es: 'Spanish',
  et: 'Estonian',
  fa: 'Persian',
  fi: 'Finnish',
  fr: 'French',
  he: 'Hebrew',
  hi: 'Hindi',
  hr: 'Croatian',
  hu: 'Hungarian',
  id: 'Indonesian',
  is: 'Icelandic',
  it: 'Italian',
  ja: 'Japanese',
  ko: 'Korean',
  lt: 'Lithuanian',
  lv: 'Latvian',
  ms: 'Malay',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt: 'Portuguese',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sl: 'Slovenian',
  sr: 'Serbian',
  sv: 'Swedish',
  sw: 'Swahili',
  th: 'Thai',
  tl: 'Tagalog',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
  zh: 'Chinese',
}

export const OpenAiSupportedModels = [
  { label: 'gpt-4-turbo', value: 'gpt-4-turbo' },
  { label: 'gpt-4-turbo-2024-04-09', value: 'gpt-4-turbo-2024-04-09' },
  { label: 'gpt-4-0125-preview', value: 'gpt-4-0125-preview' },
  { label: 'gpt-4-turbo-preview', value: 'gpt-4-turbo-preview' },
  { label: 'gpt-4-1106-preview', value: 'gpt-4-1106-preview' },
  { label: 'gpt-4-vision-preview', value: 'gpt-4-vision-preview' },
  { label: 'gpt-4', value: 'gpt-4' },
  { label: 'gpt-4-0314', value: 'gpt-4-0314' },
  { label: 'gpt-4-0613', value: 'gpt-4-0613' },
  { label: 'gpt-4-32k', value: 'gpt-4-32k' },
  { label: 'gpt-4-32k-0314', value: 'gpt-4-32k-0314' },
  { label: 'gpt-4-32k-0613', value: 'gpt-4-32k-0613' },
  { label: 'gpt-3.5-turbo', value: 'gpt-3.5-turbo' },
  { label: 'gpt-3.5-turbo-16k', value: 'gpt-3.5-turbo-16k' },
  { label: 'gpt-3.5-turbo-0301', value: 'gpt-3.5-turbo-0301' },
  { label: 'gpt-3.5-turbo-0613', value: 'gpt-3.5-turbo-0613' },
  { label: 'gpt-3.5-turbo-1106', value: 'gpt-3.5-turbo-1106' },
  { label: 'gpt-3.5-turbo-0125', value: 'gpt-3.5-turbo-0125' },
  { label: 'gpt-3.5-turbo-16k-0613', value: 'gpt-3.5-turbo-16k-0613' },
  { label: 'gpt-4o', value: 'gpt-4o' },
  { label: 'gpt-4o-2024-05-13', value: 'gpt-4o-2024-05-13' },
]
