-- Convert notes.nid from manual integer to identity column (auto-increment).
-- Uses GENERATED BY DEFAULT AS IDENTITY so existing migration scripts can
-- still insert explicit values while new rows auto-generate nid.

-- 1. Convert nid to a BY DEFAULT identity column.
--    PostgreSQL will create an internal sequence automatically.
ALTER TABLE notes
  ALTER COLUMN nid ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Advance the sequence to max(nid) + 1 so the next auto-generated nid
--    does not collide with existing rows.
DO $$
DECLARE
  max_nid integer;
BEGIN
  SELECT coalesce(max(nid), 0) INTO max_nid FROM notes;
  PERFORM setval(pg_get_serial_sequence('notes', 'nid'), max_nid + 1, false);
END $$;
